name: Build EXE

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        pip install -r requirements.txt
        pip install pyinstaller

    - name: Build EXE
      run: pyinstaller --onefile --windowed --add-data "xgb_model.pkl;." --add-data "scaler.pkl;." --add-data "scaler1.pkl;." predictor_gui/predict_gui.py

    - name: Upload EXE
      uses: actions/upload-artifact@v2
      with:
        name: PredictorGUI
        path: dist/predict_gui.exe
